export const MPR_FOLDER_NAME = '.mpr'
export const MPR_CONFIG_FILENAME = '.mprconfig.json'
export const ICON_ASSET_FOLDER = '.local/share/icons/'
export const DESKTOP_FILES_FOLDER = '.local/share/applications/'
export const MAIN_SCRIPT_NAME = 'mpr-main.sh'
